<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122102127 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE event (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            title VARCHAR(255) NOT NULL, 
            subtitle VARCHAR(255) NOT NULL, 
            image VARCHAR(255) NOT NULL, 
            address TEXT NOT NULL, 
            description TEXT DEFAULT NULL, 
            start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            display_day VARCHAR(255) NOT NULL, 
            display_time VARCHAR(255) NOT NULL, PRIMARY KEY (id))');

            
        $this->addSql('ALTER TABLE pricing_plan_benefit DROP CONSTRAINT fk_e6a62c5f29628c71');
        $this->addSql('ALTER TABLE pricing_plan_pricing_plan_feature DROP CONSTRAINT fk_d19087d429628c71');
        $this->addSql('ALTER TABLE pricing_plan_pricing_plan_feature DROP CONSTRAINT fk_d19087d46c9002d8');
        $this->addSql('DROP TABLE pricing_plan');
        $this->addSql('DROP TABLE pricing_plan_benefit');
        $this->addSql('DROP TABLE pricing_plan_feature');
        $this->addSql('DROP TABLE pricing_plan_pricing_plan_feature');
        $this->addSql('DROP TABLE "user"');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pricing_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, price INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE pricing_plan_benefit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, pricing_plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_e6a62c5f29628c71 ON pricing_plan_benefit (pricing_plan_id)');
        $this->addSql('CREATE TABLE pricing_plan_feature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE pricing_plan_pricing_plan_feature (pricing_plan_id INT NOT NULL, pricing_plan_feature_id INT NOT NULL, PRIMARY KEY (pricing_plan_id, pricing_plan_feature_id))');
        $this->addSql('CREATE INDEX idx_d19087d46c9002d8 ON pricing_plan_pricing_plan_feature (pricing_plan_feature_id)');
        $this->addSql('CREATE INDEX idx_d19087d429628c71 ON pricing_plan_pricing_plan_feature (pricing_plan_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
        $this->addSql('ALTER TABLE pricing_plan_benefit ADD CONSTRAINT fk_e6a62c5f29628c71 FOREIGN KEY (pricing_plan_id) REFERENCES pricing_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pricing_plan_pricing_plan_feature ADD CONSTRAINT fk_d19087d429628c71 FOREIGN KEY (pricing_plan_id) REFERENCES pricing_plan (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pricing_plan_pricing_plan_feature ADD CONSTRAINT fk_d19087d46c9002d8 FOREIGN KEY (pricing_plan_feature_id) REFERENCES pricing_plan_feature (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE event');
    }
}
